@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title System Context Diagram for Soccer Jerseys E-Commerce System

'Type, name, "Name", "who they are"
Person(customer, "Customer", "A customer of the Soccer Jerseys E-Commerce")
Person(employee, "Employee", "Employee of the Soccer Jerseys E-Commerce")
System(orders_system, "Soccer Jerseys E-Commerce System", "Allows customers to order soccer jerseys and employees to manage the orders and inventory")

'name => in relationship with, "name", what they do, type of relationship.
Rel(customer, orders_system, "Browses and Places orders using", "Uses")
Rel(employee, orders_system, "Manages orders and inventory", "Uses")

'SHOW_LEGEND() Removed the legend in order to display the stereotypes (person and system).
@enduml

