@startuml

package "Soccer Jerseys Microservices Application" {
    package "jerseys-service" #LightPink{
        [JerseyService] #LightGreen
        database "Jersey Repository" #Beige{
            [Jersey]
        }
        [Jersey] --> [JerseyIdentifier : Value Object]
    }

    package "teams-service" {
        [TeamService] #LightGreen
        database "Team Repository" #Beige {
            [Team]
        }
        [Team] --> [TeamIdentifier : Value Object]
    }

    package "customers-service" {
        [CustomerService] #LightGreen
        database "Customer Repository" #Beige {
            [Customer]
        }
        [Customer] --> [CustomerIdentifier : Value Object]
    }

    package "orders-service" #LightBlue {
        [OrderService] #LightGreen
        database "Order Repository" #Beige {
            [Order]
        }
        [Order] --> [OrderIdentifier : Value Object]
        [Order] --> [JerseyIdentifier : Value Object]
        [Order] --> [TeamIdentifier : Value Object]
    }
}

note "Invariant: When an order is created and a jersey is requested, the inventory of the jersey must be checked and decremented accordingly. If the jersey's quantity is less than the requested amount, an ItemUnavailableException is thrown indicating insufficient stock." as Invariant1
[OrderService] .. Invariant1

[OrderService] ..> [JerseyService] : validates inventory\nusing
[OrderService] ..> [TeamService] : fetches team details\nusing
[OrderService] ..> [CustomerService] : confirms customer\nusing

@enduml
