# Default Spring Profile
server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.soccerjerseysapplication: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


# for docker
spring:
  datasource:
    url: jdbc:mysql://mysql2/jerseys-db
    username: user
    password: pwd
    hikari.initializationFailTimeout: 60000

  jpa:
    hibernate:
      ddl-auto: none

  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always


---
# for test

#for h2
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:jerseys-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #let jpa create the schema

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true


    defer-datasource-initialization: true #turn this on to ensure that hibernate initializes the schema before loading the data

  sql:
    init:
      platform: h2
      mode: always



